name: Deploy Static Web App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Deploy Bicep template
      uses: azure/arm-deploy@v1
      with:
        scope: resourceGroup
        resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
        template: ./main.bicep
        parameters: ./parameters.json repositoryUrl=${{ github.repository }} repositoryToken=${{ secrets.GITHUB_TOKEN }} branch=${{ github.ref_name }}
        
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          echo "Deployment completed successfully!"
          # Get the Static Web App URL
          HOSTNAME=$(az deployment group show \
            --name staticWebAppDeployment \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --query properties.outputs.staticWebAppDefaultHostname.value \
            --output tsv)
          echo "::set-output name=webapp_url::https://$HOSTNAME"
          
    - name: Output Static Web App URL
      run: echo "Static Web App deployed to ${{ steps.deploy.outputs.webapp_url }}"
